"""Generate the root changelog from local histories gated by published ZIP versions.
No network, packaging, Git or publication actions. Python 3.9+ standard library.
"""
import re
from pathlib import Path

SKILLS = (
    dict(label='Student 500', name='student-500-preparation', path='Subclass500/student-500-preparation', tag='Subclass500'),
    dict(label='Visitor 600', name='visitor-600-preparation', path='Subclass600/visitor-600-preparation', tag='subclass600'),
    dict(label='Partner 801', name='partner-801-preparation', path='Subclass801/partner-801-preparation', tag='subclass801'),
    dict(label='GSM Points', name='gsm-points-preparation', path='GSM/gsm-points-preparation', tag='gsm-points'),
)


def build(root, releases):
    output = ['# Changelog', '', '<!-- Generated from each skill changelog; do not edit this file directly. -->', '',
              'Applicant-facing history grouped by independently versioned skill. Current versions are matched to published release ZIPs.', '']
    for skill in SKILLS:
        matches = [r for r in releases if r['tag_name'] == skill['tag'] and not r['draft'] and not r.get('prerelease', False)]
        if len(matches) > 1:
            raise ValueError('Duplicate published tag: '+skill['tag'])
        if not matches:
            continue
        release = matches[0]
        assets = [a for a in release['assets'] if re.fullmatch(re.escape(skill['name']) + r'-v(\d+\.\d+\.\d+)\.zip', a['name']) and a.get('state') == 'uploaded']
        if len(assets) != 1:
            raise ValueError('Expected one uploaded versioned ZIP: '+skill['tag'])
        version_match = re.fullmatch(re.escape(skill['name']) + r'-v(\d+\.\d+\.\d+)\.zip', assets[0]['name'])
        if version_match is None:
            raise ValueError('Invalid asset version')
        version = version_match.group(1)
        text = (Path(root) / skill['path'] / 'CHANGELOG.md').read_text(encoding='utf-8')
        seen = set()
        entries = []
        for block in re.split(r'(?m)^## ', text)[1:]:
            heading, _, body = block.partition('\n')
            pattern = r'(?:'+re.escape(skill['label'])+r' — )?(\d+\.\d+\.\d+)(?: — (\d{4}-\d{2}-\d{2}))?'
            match = re.fullmatch(pattern, heading)
            if not match or not body.strip():
                raise ValueError('Invalid or empty changelog entry: '+skill['name']+' / '+heading)
            entry_version, date = match.groups()
            if entry_version in seen:
                raise ValueError('Duplicate changelog version: '+entry_version)
            seen.add(entry_version)
            if tuple(map(int, entry_version.split('.'))) <= tuple(map(int, version.split('.'))):
                entries.append((entry_version, date, body.strip()))
        if version not in seen:
            raise ValueError('Missing published version in changelog: '+skill['name']+' '+version)
        output += ['## '+skill['label'], '', f'Published version: **{version}** · [Release](https://github.com/ScriptSavvy/AustraliaVisaSkills/releases/tag/{skill["tag"]})', '']
        for entry_version, date, body in sorted(entries, key=lambda e: tuple(map(int, e[0].split('.'))), reverse=True):
            output += ['### '+entry_version+(' — '+date if date else ''), body, '']
    return '\n'.join(output).rstrip()+'\n'


if __name__ == '__main__':
    import argparse
    import json
    import os
    import sys
    import tempfile

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', required=True, type=Path, help='Public repository root')
    parser.add_argument('--releases', required=True, type=Path, help='GitHub releases API JSON snapshot')
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        releases = json.loads(args.releases.read_text(encoding='utf-8'))
        if not isinstance(releases, list) or not releases:
            raise ValueError('Expected a nonempty release list; refusing to erase history')
        content = build(args.root, releases)
        if not any(r.get('tag_name') in {s['tag'] for s in SKILLS} and not r.get('draft') and not r.get('prerelease') for r in releases):
            raise ValueError('No supported published releases; refusing to erase history')
        target = args.root / 'CHANGELOG.md'
        if args.check:
            if not target.exists() or target.read_text(encoding='utf-8') != content:
                raise ValueError('Root CHANGELOG.md needs regeneration')
            print('PASS: root changelog matches published-version-gated histories')
        else:
            if target.is_symlink():
                raise ValueError('Refusing symlink output')
            with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=args.root, prefix='.changelog-', delete=False) as handle:
                pending = Path(handle.name)
                handle.write(content)
            try:
                os.replace(pending, target)
            finally:
                pending.unlink(missing_ok=True)
            print('Updated '+str(target))
    except (ValueError, OSError, KeyError, TypeError) as error:
        print('ERROR: '+str(error), file=sys.stderr)
        sys.exit(1)
